# Generated by Django 4.1.1 on 2022-11-07 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('reg_plate', models.CharField(max_length=50, unique=True)),
                ('mileage', models.IntegerField()),
                ('last_service_mileage', models.IntegerField(default=models.IntegerField())),
                ('service_interval', models.IntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField(null=True)),
                ('service_type', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('date_fixed', models.DateField(null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField(null=True)),
                ('liters', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=70, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'ordering': ['-mileage'],
            },
        ),
    ]
